name: Deploy Angular to Monster ASP via FTP

on:
  push:
    branches:
      - master  # Change if your deployment branch is different
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Change this based on your Angular requirements

      - name: Install Dependencies
        run: npm ci  # Ensures a clean and fast install
        working-directory: ./Client/  
        
      - name: Build Angular App
        run: npm run build -- --output-path=dist
        working-directory: ./Client/

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: "site16186.siteasp.net"
          username: "${{ secrets.NG_FTP_USERNAME }}"
          password: "${{ secrets.NG_FTP_PASSWORD }}"
          local-dir: "./dist/"  # This is where the Angular build is stored
          server-dir: "/wwwroot/"  # Change this to your Monster ASP deployment path
          passive: true  # Enable passive mode if needed
          dangerous-clean-slate: true  # Deletes old files before upload
