name: Deploy to Monster ASP

on:
  workflow_dispatch:
  push:
    branches:
      - master  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Change this to match your .NET version
          
      - name: Restore Dependencies
        run: dotnet restore
        working-directory: ./API/src/API
        
      - name: Restore appsettings.json
        run: echo '${{ secrets.APPSETTINGS_JSON }}' > ./API/src/API/appsettings.json

      - name: Build and Publish
        run: dotnet publish -c Release -o ../../../publish
        working-directory: ./API/src/API

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
         server: "site16186.siteasp.net"  # Your Monster ASP FTP server
         username: ${{ secrets.FTP_USERNAME }}
         password: ${{ secrets.FTP_PASSWORD }}
         local-dir: "./publish/"
         server-dir: "/wwwroot/"
         dangerous-clean-slate: true
