name: Deploy to Monster ASP

on:
  workflow_dispatch:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Change to your .NET version
          
      - name: Restore Dependencies
        run: dotnet restore './API/src/API/API.csproj'

      - name: Build and Publish
        run: dotnet publish './API/src/API/API.csproj' -c Release -o ./publish

      - name: Deploy to Monster ASP
        uses: azure/webapps-deploy@v2
        with:
          app-name: "balancerapi"  
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          package: ./publish
